mujoco_server:
  ros__parameters:
    MujocoPlugins:
      names:
        - mujoco_ros2_control
      mujoco_ros2_control:
        type: mujoco_ros2_control::MujocoRos2ControlPlugin
        hardware:
          type: mujoco_ros_control/RobotHW
          control_period: 0.001
        params:
          namespace: ""
          robot_description_node: "robot_state_publisher"
          robot_description: "robot_description"

controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    franka_left_robot_state_broadcaster:
      type: franka_robot_state_broadcaster/FrankaRobotStateBroadcaster
    franka_right_robot_state_broadcaster:
      type: franka_robot_state_broadcaster/FrankaRobotStateBroadcaster
    franka_left_robot_model_broadcaster:
      type: franka_robot_state_broadcaster/FrankaRobotModelBroadcaster
    franka_right_robot_model_broadcaster:
      type: franka_robot_state_broadcaster/FrankaRobotModelBroadcaster
    dual_joint_impedance_example_controller:
      type: franka_example_controllers/MultiJointImpedanceExampleController
    dual_joint_velocity_example_controller:
      type: franka_example_controllers/DualJointVelocityExampleController
    sim_multi_mode_controller:
      type: multi_mode_controller/MultiModeController
    dual_panda_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    
franka_left_robot_state_broadcaster:
  ros__parameters:
    arm_id: mj_left
    frequency: 30

franka_right_robot_state_broadcaster:
  ros__parameters:
    arm_id: mj_right
    frequency: 30

franka_left_robot_model_broadcaster:
  ros__parameters:
    arm_id: mj_left
    frequency: 30

franka_right_robot_model_broadcaster:
  ros__parameters:
    arm_id: mj_right
    frequency: 30
    
dual_joint_impedance_example_controller:
  ros__parameters:
    arm_count: 2
    arm_1:
      arm_id: mj_left
      k_gains:
        - 24.0
        - 24.0
        - 24.0
        - 24.0
        - 10.0
        - 6.0
        - 2.0
      d_gains:
        - 2.0
        - 2.0
        - 2.0
        - 1.0
        - 1.0
        - 1.0
        - 0.5
    arm_2:
      arm_id: mj_right
      k_gains:
        - 24.0
        - 24.0
        - 24.0
        - 24.0
        - 10.0
        - 6.0
        - 2.0
      d_gains:
        - 2.0
        - 2.0
        - 2.0
        - 1.0
        - 1.0
        - 1.0
        - 0.5
    
dual_joint_velocity_example_controller:
  ros__parameters:
    arm_1:
      arm_id: mj_left
    arm_2:
      arm_id: mj_right

sim_multi_mode_controller:
  ros__parameters:
    arm_count: 2
    arm_1:
      arm_id: mj_left
    arm_2:
      arm_id: mj_right
    controllers: ["panda_joint_impedance_controller", 
                  "panda_joint_velocity_controller",
                  "comless_coupled_dual_cartesian_impedance_controller", 
                  "dual_cartesian_impedance_controller",
                  "des_coupled_dual_cartesian_impedance_controller"]
    resources:
        comless_coupled_dual_cartesian_impedance_controller: ["mj_left&mj_right"]
        dual_cartesian_impedance_controller: ["mj_left&mj_right"]
        des_coupled_dual_cartesian_impedance_controller: ["mj_left&mj_right"]
        panda_joint_impedance_controller: ["mj_left","mj_right"]
        panda_joint_velocity_controller: ["mj_left","mj_right"]
    start_controllers:
        names: ["dual_cartesian_impedance_controller"]
        resources:
            dual_cartesian_impedance_controller: ["mj_left&mj_right"]

dual_panda_arm_controller:
  ros__parameters:
    joints:
      - mj_left_joint1
      - mj_left_joint2
      - mj_left_joint3
      - mj_left_joint4
      - mj_left_joint5
      - mj_left_joint6
      - mj_left_joint7
      - mj_right_joint1
      - mj_right_joint2
      - mj_right_joint3
      - mj_right_joint4
      - mj_right_joint5
      - mj_right_joint6
      - mj_right_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0